### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by nicomelnyk** [Antoinegtir/background-remover#1]
Hi! 
I want to try this package. Looks amazing and promising.
Getting this error while im calling removeBackground() method: 
"MissingPluginException(No implementation found for method removeBackground on channel background_remover)"
What could the problem be?
I am using chrome as emulator

**Comment by nicomelnyk** [comment]
It works when I use a phone as emulator. Seems like a web related problem

**Comment by Antoinegtir** [comment]
> It works when I use a phone as emulator. Seems like a web related problem

As said on the pub dev website the package is currently aivailable only for android

**Comment by nicomelnyk** [comment]
didnt see it, my bad
works great on android. cheers mate

**Comment by Antoinegtir** [comment]
> didnt see it, my bad
> 
> works great on android. cheers mate

Thanks maybe it will be deploy on others platform in the future 🤷‍♂️

**Comment by Kaizodo** [comment]
run ```flutter clean```  then rebuilt the app it will work

**Comment by Veere6** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method removeBackground on channel background_remover)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      BackgroundRemover.removeBackground (package:background_remover/src/background_remover_platform.dart:8:12)
<asynchronous suspension>
#2      removeBackground (package:background_remover/background_remover.dart:7:10)
<asynchronous suspension>
#3      _ResultViewState._removeBackground (package:wardrobe/view/result_view.dart:352:20)
<asynchronous suspension>.   working fine in android but in ios i am facing this issue
